# Generated by Django 2.1.7 on 2019-04-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_follower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_auto_20190425_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reason',
            new_name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(
                blank=True, related_name='favorited_articles', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='favourite_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='article',
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='article_id', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
